
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/DeveloperiMichael/ZJSpecs.git'


platform:ios, '9.0'

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'


  pod 'IQKeyboardManager'

  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end
